/*******************************************************************************
 * Copyright (c) 2011  University of Western Australia. All rights reserved.
 * 
 * This file is part of The Ark.
 * 
 * The Ark is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 3
 * of the License, or (at your option) any later version.
 * 
 * The Ark is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************/
package au.org.theark.core.model.lims.entity;

// Generated 15/06/2011 1:22:58 PM by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import au.org.theark.core.model.Constants;

/**
 * BioSampletype generated by hbm2java
 */
@Entity
@Table(name = "address", schema = Constants.LIMS_TABLE_SCHEMA)
public class Address implements java.io.Serializable {


	private static final long	serialVersionUID	= -6857329961855700249L;
	private Long					id;
	private String					line1;
	private String					line2;
	private String					line3;
	private Integer					code;
	private AddressType				addressType;
	private Boolean					isCurrent;

	public Address() {
	}

	public Address(Long id, String line1, String line2,
			String line3, Integer code, AddressType addressType, Boolean isCurrent) {
		this.id = id;
		this.line1 = line1;
		this.line2 = line2;
		this.line3 = line3;
		this.code = code;
		this.addressType = addressType;
		this.isCurrent = isCurrent;
	}

	/**
	 * @return the id
	 */
	@Id
	@SequenceGenerator(name = "address_generator", sequenceName = "ADDRESS_SEQUENCE")
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "address_generator")
	public Long getId() {
		return this.id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * @return the line1
	 */
	@Column(name = "LINE1")
	public String getLine1() {
		return line1;
	}

	/**
	 * @param line1 the line1 to set
	 */
	public void setLine1(String line1) {
		this.line1 = line1;
	}

	/**
	 * @return the line2
	 */
	@Column(name = "LINE2", nullable = false)
	public String getLine2() {
		return this.line2;
	}

	/**
	 * @param line2 the line2 to set
	 */
	public void setLine2(String line2) {
		this.line2 = line2;
	}

	/**
	 * @return the line3
	 */
	@Column(name = "LINE3")
	public String getLine3() {
		return this.line3;
	}

	/**
	 * @param line3 the line3 to set
	 */
	public void setLine3(String line3) {
		this.line3 = line3;
	}

	/**
	 * @return the code
	 */
	@Column(name = "CODE")
	public Integer getCode() {
		return code;
	}

	/**
	 * @param code the code to set
	 */
	public void setCode(Integer Code) {
		this.code = Code;
	}

	/**
	 * @return the addressType
	 */
	@Column(name = "ADDRESS_TYPE")
	public AddressType getAddressType() {
		return addressType;
	}

	/**
	 * @param addressType the addressType to set
	 */
	public void setAddressType(AddressType addressType) {
		this.addressType = addressType;
	}

	/**
	 * @return the isCurrent
	 */
	@Column(name = "IS_CURRENT")
	public Boolean getIsCurrent() {
		return isCurrent;
	}

	/**
	 * @param isCurrent the isCurrent to set
	 */
	public void setIsCurrent(Boolean isCurrent) {
		this.isCurrent = isCurrent;
	}	
}
